version: '2'
services:
    store:
        build:
            context: ./docker
            dockerfile: Dockerfile-store
        container_name: comic-store-apache
        ports:
            - '80:80'
        volumes:
            - .:/var/www/html
        links:
            - db:mysqldb
        command: /bin/bash /var/www/html/docker/test-api.sh

    db:
        build:
            context: ./docker
            dockerfile: Dockerfile-db
        env_file:
          - docker.env
        container_name: comic-store-db
        volumes:
            - ./data/db:/var/lib/mysql"
        environment:
            - MYSQL_DATABASE=store
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=root
            - TZ=Europe/Madrid
        ports:
            - 3307:3306
        command: mysqld --user=root --verbose --skip-sync-frm --innodb_flush_log_at_trx_commit=0 --innodb-support-xa=0 --bind-address=0.0.0.0 --query-cache-type=1

volumes:
  db:
    driver: "local"
