api_platform:
    mapping:
        paths:
          - '%kernel.project_dir%/src/Accounts/Domain/Model'
          - '%kernel.project_dir%/src/Backend/Domain/Model'
          - '%kernel.project_dir%/src/Catalog/Domain/Model'
          - '%kernel.project_dir%/src/Common/Domain/Model'
