signup:
    path: /signup
    controller: App\Accounts\Infrastructure\Controller\UserController::signup

users:
    path: /users
    controller: App\Accounts\Infrastructure\Controller\UserController::list
