heroes:
    path: /heroes
    controller: App\Catalog\Infrastructure\Controller\CatalogController::allHeroes

heroe:
    path: /heroe/{id}
    controller: App\Catalog\Infrastructure\Controller\CatalogController::getHeroe